/**
 * Weeping Willows Walter — Episode metadata extracted from lore analysis files.
 * Source: episode-01.md through episode-28.md
 */

export interface EpisodeMeta {
  num: number;
  title: string;
  premise: string;
  tone: string;
  characters: string[];
  locations: string[];
  durationSec: number;
  audioSignature: string;
  distinctive: string;
}

export const EPISODES: EpisodeMeta[] = [
  {
    num: 1,
    title: "Weeping Willows Walter",
    premise: "A miniature diorama of a suburban house at night. A miniature figure stands in the yard, illuminated by a light source, casting a shadow on the garage door. The episode ends with the figure being called out by name, creating a sense of mystery and intrigue.",
    tone: "melancholy, mysterious, unease, curiosity, sadness",
    characters: ["Walter"],
    locations: ["Front Yard", "House", "Garage Door", "Landscape", "Trees"],
    durationSec: 89,
    audioSignature: "Slow melancholic instrumental piece with strings and mournful melody, traffic sounds throughout, voiceover calling 'Walter.'",
    distinctive: "The episode is distinctive for its slow pacing, its lack of explanation, and its focus on creating a specific mood and atmosphere.",
  },
  {
    num: 2,
    title: "Totality",
    premise: "A nighttime scene outside a trailer home. A figure stands on the porch steps observing something in the night sky. Another figure is seen in the yard. The episode ends with a shot of the moon through tree branches, suggesting the characters are observing a lunar event.",
    tone: "unease, curiosity, mysterious, suspenseful",
    characters: ["Walter", "narrator"],
    locations: ["Trailer Home", "Porch", "Yard", "Street", "Moon", "Tree Branches"],
    durationSec: 90,
    audioSignature: "Mix of ambient sounds and eerie orchestral elements, wind and crickets, dog barking, cryptic dialogue about totality and the moon.",
    distinctive: "The combination of eerie music, cryptic dialogue, and unsettling visuals makes this episode distinctive.",
  },
  {
    num: 3,
    title: "Birthday Boy",
    premise: "Walter, a miniature figure, is introduced on his birthday. A narrator sets the scene, explaining it's Walter's special day and inviting him to a dog parade in the front yard. The episode showcases several miniature dog figures, each with a brief introduction.",
    tone: "lighthearted, amused, childlike wonder",
    characters: ["Walter", "Comet", "Rusty", "Chowbie", "Coco"],
    locations: ["Front Yard", "House", "Porch"],
    durationSec: 31,
    audioSignature: "Whimsical, slightly melancholic organ tune, bird sounds, dog barking, nostalgic and quirky atmosphere.",
    distinctive: "The use of miniature figures and a whimsical narrative creates a unique and charming experience.",
  },
  {
    num: 4,
    title: "Birthday Boy Part 2",
    premise: "Continues the story of Walter and his dogs, focusing on the appearance of a black cat that seems to cause concern. The narrator questions if the cat is Walter, then expresses concern about Rusty's whereabouts, eventually finding him safe with the man.",
    tone: "curiosity, concern, relief, slightly unsettling",
    characters: ["Walter", "Rusty", "Cocoa", "black cat"],
    locations: ["Yard", "House", "Fence", "Mailbox"],
    durationSec: 66,
    audioSignature: "Melancholy, slightly eerie classical music, dog meows and barks, smooth fades between scenes.",
    distinctive: "The combination of the miniature world, the melancholic music, and the slightly unsettling narrative creates a unique and memorable experience.",
  },
  {
    num: 5,
    title: "Nice and Easy Does It",
    premise: "Walter receives a delivery of new shutters for his house. He and his dog Rusty embark on a home improvement project, carefully installing the shutters and reflecting on the deeper meaning of building a home and shaping one's dreams. The episode ends with Walter admiring the completed work.",
    tone: "warmth, nostalgia, contentment, accomplishment",
    characters: ["Walter", "Rusty"],
    locations: ["House", "Landscape", "Trees", "Delivery Truck", "Back of House"],
    durationSec: 260,
    audioSignature: "Gentle, nostalgic orchestral music, calm and reflective. Truck horn, hammering, dog bark. Walter's calm reflective voiceover.",
    distinctive: "The episode is distinctive for its slow pacing, reflective narration, and focus on the deeper meaning of home and belonging.",
  },
  {
    num: 6,
    title: "Happy Earth Day",
    premise: "A short black and white 'Happy Earth Day' message. Begins with an aerial view of a person and a dog lying on the grass. Transitions to a shot of many birds flying in the sky with the text 'Happy Earth Day' appearing. Ends with the aerial view of the person and the dog.",
    tone: "peace, appreciation for nature, touch of melancholy",
    characters: ["Rusty"],
    locations: ["Grass", "Sky"],
    durationSec: 25,
    audioSignature: "Somber melancholic instrumental transitioning to uplifting hopeful melody when birds appear. Dog sounds (whining, barking), bird sounds (chirping, flapping). Voice says 'Happy Earth Day Rusty.'",
    distinctive: "The minimalist approach, the black and white aesthetic, and the focus on nature and companionship make this episode distinctive.",
  },
  {
    num: 7,
    title: "Walter_IG_07",
    premise: "A static shot of a miniature diorama depicting a house and trailer in a forested landscape under a vibrant aurora borealis. A voiceover expresses regret for leaving someone named Walter, suggesting themes of loss, remorse, and the enduring beauty of nature as a backdrop to personal reflection.",
    tone: "melancholy, nostalgia, longing",
    characters: ["Walter"],
    locations: ["House", "Camper Trailer", "Forested Landscape", "Night Sky"],
    durationSec: 28,
    audioSignature: "Slow, melancholic instrumental music, ambient or neo-classical. Male voiceover with regret: 'Walter,' 'It's beautiful,' 'I'm sorry I left you.'",
    distinctive: "The combination of the miniature setting, the stunning aurora, and the voiceover's heartfelt regret creates a powerful and memorable emotional experience.",
  },
  {
    num: 8,
    title: "Weeping Willows Walter",
    premise: "Walter finds himself lost and confused in the void. A wise mushroom observes Walter's bewilderment, knowing the story will eventually reveal itself. Walter eventually gasps, seemingly on the verge of understanding, but the meaning remains elusive. The episode ends with a promise that the story will come to them someday.",
    tone: "gentle curiosity, anticipation, dreamy",
    characters: ["Walter", "Mushroom"],
    locations: ["Void", "Abstract Landscape"],
    durationSec: 90,
    audioSignature: "Ambient electronic music with slow tempo and dreamy, slightly melancholic mood. Whooshing sound effect. Narration about the void and Walter's confusion.",
    distinctive: "The whimsical narrative, the friendly mushroom character, and the ambiguous ending make this episode distinctive.",
  },
  {
    num: 9,
    title: "Rusty's Surprise",
    premise: "A miniature diorama of a suburban backyard scene. A boy is playing with a ball, a dog is lounging, and a man is standing nearby. The creator uses tweezers to manipulate miniature objects. The episode ends abruptly with a loud crash and 'TO BE CONTINUED...' suggesting a cliffhanger.",
    tone: "suspense, anticipation, peaceful then jarring",
    characters: ["Rusty", "boy", "dog", "man"],
    locations: ["Backyard", "House", "Street Lamp", "Fence", "Trees", "Picnic Table"],
    durationSec: 26,
    audioSignature: "Gentle acoustic music with slightly melancholic mood, bird chirping. Loud crashing sound at the end. Voice yells 'Rusty!'",
    distinctive: "The abrupt ending and the 'TO BE CONTINUED...' message are distinctive elements that create suspense and encourage viewers to watch the next episode.",
  },
  {
    num: 10,
    title: "Weeping Willows Walter Season 2 Teaser",
    premise: "Teaser for Season 2. Opens with a miniature model of a suburban house at night with streetlights and a dilapidated yard. The scene is disrupted by the sound of a vehicle and a giant hand placing a small trailer in front of the house. A voiceover delivers a cryptic line suggesting a return to a familiar but perhaps unsettling home.",
    tone: "curiosity, anticipation, slight dread, mystery",
    characters: ["Walter", "Rusty"],
    locations: ["Suburban House", "Yard", "Trailer"],
    durationSec: 34,
    audioSignature: "Cricket sounds transitioning to slow melancholic piano melody. Engine sounds, trailer placement, door opening, dog bark. Voiceover: 'Hop on out, Rusty. We're home now.'",
    distinctive: "The combination of the miniature world, the cryptic voiceover, and the eerie atmosphere sets it apart. The out-of-scale drill in the background adds to the surrealism.",
  },
  {
    num: 11,
    title: "Just some patience, Rusty",
    premise: "A miniature backyard scene with a house, pool, and barbecue. A character, presumably Walter, is grilling while a tiny dog named Rusty patiently waits nearby. The episode focuses on the anticipation of the food being cooked and the bond between the owner and pet.",
    tone: "amusement, heartwarming connection, patience",
    characters: ["Walter", "Rusty"],
    locations: ["Backyard", "House", "Pool", "Barbecue Grill", "Trees"],
    durationSec: 70,
    audioSignature: "Gentle acoustic music with folksy feel, calm and relaxed. Bird chirping. Narration: 'You like your new spot, Rusty?' 'We're real close, just some patience.'",
    distinctive: "The episode is distinctive for its focus on a simple, everyday moment and its gentle, heartwarming tone.",
  },
  {
    num: 12,
    title: "BTS EP 1 Walters house",
    premise: "A behind-the-scenes look at the creation of a miniature set for stop-motion animation. Depicts a miniature version of Walter White's house from 'Breaking Bad,' complete with miniature figures, a trailer, and landscaping.",
    tone: "awe, appreciation for craftsmanship",
    characters: [],
    locations: ["Walter White's House", "Gravel Driveway", "White Picket Fence", "Trailer", "Weeping Willow Tree"],
    durationSec: 9,
    audioSignature: "Acoustic, mellow, slightly melancholic folk-like music. Calm, contemplative mood.",
    distinctive: "The combination of a familiar setting (Walter White's house) with the unique art form of miniature set design.",
  },
  {
    num: 13,
    title: "Weeping Willows Walter",
    premise: "A miniature world featuring Walter and his dog Rusty in a whimsical, autumnal setting with miniature trees, pumpkins, and a park bench under a bright blue sky. The video culminates in a shot of Walter floating in the sky. A reflection on life and the simple joys found within it, presented through a surreal and dreamlike lens.",
    tone: "wonder, nostalgia, touch of melancholy",
    characters: ["Walter", "Rusty"],
    locations: ["Park Bench", "Weeping Willow Tree", "Pumpkins", "Flowers", "Lamppost", "Sky"],
    durationSec: 17,
    audioSignature: "Melancholy and whimsical instrumental music, possibly classical or orchestral-inspired. Dog bark. Voiceover: 'Weeping Willows Walter. This is me, and this is my life. And my dog Rusty.'",
    distinctive: "The unique 'weeping willow' tree made of rope-like material, the miniature scale of the world, and the surreal narrative are all distinctive elements.",
  },
  {
    num: 14,
    title: "The Sound of Someone Remembering You",
    premise: "Walter returns to his childhood home, which is now dilapidated and overgrown. He is greeted by his childhood friends and dog Rusty, who are happy to see him. Walter is struck by the contrast between his memories and the current state of the place.",
    tone: "melancholic nostalgia, bittersweet",
    characters: ["Walter", "Rusty", "Friend"],
    locations: ["Childhood Home", "Yard", "Garage", "Picnic Table", "Weeping Willow", "Dirt Road", "Camper Truck"],
    durationSec: 88,
    audioSignature: "Melancholic, slow-tempo instrumental piece with nostalgic and slightly sad mood. Bird sounds, car engine, dog sounds, bell. Dialogue between Walter and friends.",
    distinctive: "The episode's distinctive quality lies in its ability to evoke a strong emotional response through miniature models and a melancholic soundtrack.",
  },
  {
    num: 15,
    title: "Walter_IG_15",
    premise: "A surreal, miniature diorama scene at night. A lone astronaut figure stands atop a giant cookie sandwich, with a suburban house visible in the background. The scene is bathed in blue and orange lighting, creating a dreamlike, slightly unsettling atmosphere. Themes of isolation, observation, and the feeling of being watched.",
    tone: "curiosity, wonder, touch of unease",
    characters: ["Astronaut figure"],
    locations: ["Cookie Sandwich", "Suburban House", "Trees", "Picket Fence", "Shrubbery"],
    durationSec: 31,
    audioSignature: "Electronic, synth-heavy instrumental track. Slightly melancholic and mysterious, moderate tempo, subdued energy.",
    distinctive: "The dreamlike quality and the sense of isolation conveyed through the visuals and music.",
  },
  {
    num: 16,
    title: "Post Turkey Cleaning",
    premise: "A miniature diorama of a backyard scene where someone is cleaning up after a Thanksgiving celebration. A giant hand manipulates miniature tools and objects within the diorama, creating a whimsical and slightly surreal effect.",
    tone: "amusement, wonder",
    characters: [],
    locations: ["Backyard", "Dilapidated Car", "Pool", "Gravel Path", "Weeping Willow", "Trees"],
    durationSec: 30,
    audioSignature: "Upbeat, jazzy, slightly quirky music. Moderate tempo, fairly high energy. No distinct sound effects or voiceover.",
    distinctive: "The combination of a mundane task (cleaning) with a fantastical presentation (miniature world, giant hand) makes this episode unique.",
  },
  {
    num: 17,
    title: "Faster Forward",
    premise: "Walter attempts to clean up his neglected property but struggles. His neighbor encourages him to 'fast forward' the process, leading to a montage of cleaning at accelerated pace. Walter becomes nauseous from the speed, realizing he's having a panic attack. The neighbors complete the cleanup, but Walter feels he owes them something.",
    tone: "amusement, empathy, anxiety, unease",
    characters: ["Walter", "Neighbor", "dog"],
    locations: ["House", "Yard", "Porch", "Weeping Willow", "Rural Landscape"],
    durationSec: 89,
    audioSignature: "Upbeat, quirky, slightly frantic music with vintage feel. Tempo increases during fast-forward montage. Cleaning sound effects (raking, scrubbing), whoosh sounds, dramatic sting. Journal-style narration and neighbor dialogue.",
    distinctive: "The episode's distinctive element is its ability to convey complex emotions (anxiety, panic) through a simple, visually appealing format.",
  },
  {
    num: 18,
    title: "Episode delayed due to exploration",
    premise: "A surreal, dreamlike landscape bathed in purple light. Walter, a figure in a fedora and trench coat, explores this miniature world filled with oversized objects like a mushroom lamp and a child's pool. The episode ends with Walter silhouetted against a bright, otherworldly light source.",
    tone: "curiosity, uncanny, exploration",
    characters: ["Walter"],
    locations: ["Miniature Landscape", "Mushroom Lamp", "Pool", "Street Lamp", "Small Building"],
    durationSec: 11,
    audioSignature: "Electronic music with slow tempo and slightly unsettling, dreamlike mood. Synth-heavy sound.",
    distinctive: "The combination of the miniature scale, the purple lighting, and the mysterious character of Walter creates a distinctive visual style.",
  },
  {
    num: 19,
    title: "Episode delayed due to exploration",
    premise: "A shadowy figure, presumably Walter, approaches a mysterious, glowing structure in a dark, purple-lit environment. Walter's exploration is the reason for a delay in the series. Curiosity and the allure of the unknown.",
    tone: "intrigue, anticipation",
    characters: ["Walter"],
    locations: ["House", "Glowing Cylindrical Structure"],
    durationSec: 13,
    audioSignature: "Electronic music with slow tempo and slightly eerie, suspenseful mood. Driving beat adding urgency.",
    distinctive: "The mysterious glowing structure and the lack of explanation contribute to the episode's intrigue.",
  },
  {
    num: 20,
    title: "Griswold?",
    premise: "A playful announcement that the next installment is delayed due to the creator exploring new tools. Transitions to a whimsical, miniature Christmas scene reminiscent of the Griswold family's over-the-top decorations, suggesting a possible theme for the upcoming episode.",
    tone: "amusement, anticipation",
    characters: ["Walter"],
    locations: ["Foggy Blue-lit Environment", "Miniature Christmas Scene", "Gingerbread House", "Fence"],
    durationSec: 21,
    audioSignature: "Scene 1: Slow, slightly eerie synth track. Scene 2: Audio unavailable.",
    distinctive: "The combination of a mysterious opening with a whimsical Christmas theme, hinting at the creator's unique style.",
  },
  {
    num: 21,
    title: "Before It Dries Out",
    premise: "Walter encounters Sam, who is selling 'Real Live Santas.' Walter and Rusty are looking for a Christmas tree, but Walter is skeptical of Sam's Santas. Sam insists his Santas are scientifically accurate. Walter eventually relents and buys one, but only because it has his hand.",
    tone: "amusement, nostalgia, touch of cynicism",
    characters: ["Walter", "Rusty", "Sam"],
    locations: ["Snowy Landscape", "House with Christmas Lights", "LIVE SANTAS Sign", "Truck"],
    durationSec: 89,
    audioSignature: "Whimsical, slightly melancholic instrumental piece, piano or strings-based. Nostalgic and slightly eerie. Dog barks, truck engine. Dialogue between Walter and Sam.",
    distinctive: "The episode's blend of Christmas nostalgia, dark humor, and social commentary. The 'Real Live Santas' concept is particularly bizarre and memorable.",
  },
  {
    num: 22,
    title: "Walter_IG_22",
    premise: "A whimsical, slightly surreal Christmas scene featuring a snow-covered landscape with a decorated house and a giant pair of lips on a cartoon body. The scene is bathed in blue light, creating a dreamy, slightly unsettling atmosphere. Juxtaposition of traditional Christmas imagery with the bizarre and unexpected.",
    tone: "amusement, curiosity, touch of unease",
    characters: [],
    locations: ["Snow-covered Landscape", "Decorated House", "Christmas Trees", "Street Lamp"],
    durationSec: 14,
    audioSignature: "Jazzy, lo-fi instrumental piece. Relaxed, slightly melancholic mood, moderate tempo, low energy, chill atmosphere.",
    distinctive: "The episode is distinctive for its bizarre and unexpected imagery, creating a memorable and thought-provoking experience.",
  },
  {
    num: 23,
    title: "Walter_IG_23",
    premise: "A miniature Christmas scene after a heavy snowfall. Walter is dismayed to see the extent of the snow, which has buried the mailbox and partially submerged Santa Claus. He tries to shovel the snow but it doesn't work. The episode ends with Walter and Rusty taking shortcuts to get the job done.",
    tone: "amusement, relatability, dark humor",
    characters: ["Walter", "Rusty"],
    locations: ["Snow-covered Landscape", "House", "Mailbox", "Roof", "Yard"],
    durationSec: 85,
    audioSignature: "Melancholy, slightly whimsical instrumental music. Truck engine, dog bark, shovel sounds. Narration about snowfall and shoveling.",
    distinctive: "The combination of dark humor, miniature scale, and relatable winter weather themes.",
  },
  {
    num: 24,
    title: "Walters Living Nativity Pageant",
    premise: "A miniature living nativity scene narrated with a humorous twist. The traditional angel's announcement is interrupted by Walter, who complains about the noise and introduces a plastic skater figure on a Coca-Cola ice block. The episode subverts expectations by blending the sacred with the mundane.",
    tone: "amusement, surprise, holiday cheer",
    characters: ["Walter", "Sam", "Angel"],
    locations: ["Nativity Scene", "House", "Christmas Trees", "Coca-Cola Ice Block", "Red Platform"],
    durationSec: 45,
    audioSignature: "Traditional Christmas music shifting to upbeat, slightly jazzy tune. Angel's sacred text and Walter's humorous interruptions.",
    distinctive: "The unexpected introduction of the skater figure and the humorous dialogue make this episode stand out.",
  },
  {
    num: 25,
    title: "The Living Body of Santa!",
    premise: "A whimsical, slightly spooky Christmas village scene with fog, colorful lights, and miniature figures. A hand appears throughout, manipulating the figures. Playful subversion of traditional Christmas imagery, blending it with a Halloween-esque vibe.",
    tone: "amusement, quirky fun, hint of uncanny",
    characters: ["Santa"],
    locations: ["Christmas Village", "House", "Candy Cane Trees", "Sleigh", "Presents"],
    durationSec: 18,
    audioSignature: "Fast-paced, high-energy electronic track with slightly spooky, carnival-esque feel. Distorted, echoing laugh. Voiceover: 'Well, you get to meet Santa here in a mixed-up way. You try to hitch a ride, but he's here to slay.'",
    distinctive: "The slightly unsettling tone, the hand manipulating the figures, and the 'slay' line.",
  },
  {
    num: 26,
    title: "Twitch your living body!",
    premise: "A house covered in snow at night, illuminated by blue light. A voiceover expresses frustration and impatience towards Walter, urging him to 'twitch his stupid living body' and 'move.' The narrative suggests everyone is waiting for Walter to make a decision.",
    tone: "unease, suspense, touch of dark humor",
    characters: ["Walter"],
    locations: ["House", "Front Yard", "Snowman"],
    durationSec: 30,
    audioSignature: "Low, droning ambient music with slightly unsettling tone. Male voiceover with strained tone demanding Walter move.",
    distinctive: "The combination of mundane setting (suburban house) with surreal lighting and an aggressive, mysterious voiceover.",
  },
  {
    num: 27,
    title: "It's This Christmas Miracle",
    premise: "Walter celebrates the first snowfall of the year in his miniature Christmas village. He interacts with his dog Rusty, builds a snowman, and playfully argues with Sam, who urges him to go to bed. The episode ends with Walter catching snowflakes with Rusty, reveling in the magic of the season.",
    tone: "nostalgia, warmth, festive cheer",
    characters: ["Walter", "Rusty", "Sam"],
    locations: ["Christmas Village", "House", "Sleigh", "Snow", "Truck"],
    durationSec: 87,
    audioSignature: "Whimsical, slightly melancholic Christmas music. Dog barking, wind sounds. Walter and Sam dialogue, playful snowflake-catching.",
    distinctive: "The whimsical miniature world, the playful interaction between Walter and Rusty, and the nostalgic Christmas atmosphere.",
  },
  {
    num: 28,
    title: "Midnight Munch",
    premise: "A nighttime scene in a miniature neighborhood where Walter is disturbed by a badger raiding the garbage. His neighbors, awakened by the commotion, dismiss his concerns and return home. The episode ends with Walter standing atop a giant cookie, suggesting his late-night snacking habits are the real source of his nocturnal disturbances.",
    tone: "amusement, surreal humor, relatable guilt",
    characters: ["Walter", "Rusty", "Neighbor 1", "Neighbor 2", "Badger"],
    locations: ["Neighborhood", "House", "Street Lamp", "Trash Can", "Giant Cookie"],
    durationSec: 87,
    audioSignature: "Whimsical, slightly eerie tune reminiscent of a children's story or off-kilter fairy tale. Rummaging sounds, animal noises (growling, snarling), gunshot, doorbell. Dialogue between Walter and neighbors.",
    distinctive: "The episode's blend of mundane suburban life with surreal elements and a touch of horror.",
  },
];
