import type { ArcTemplate } from "./types";

export const ARC_TEMPLATES: ArcTemplate[] = [
  {
    id: "three-act",
    name: "Classic 3-Act",
    description: "Setup → Confrontation → Resolution. The universal story structure.",
    beats: [
      { label: "Hook", description: "Grab attention in the first 3 seconds", color: "#f97316", order: 0 },
      { label: "Setup", description: "Introduce the world, characters, and stakes", color: "#f97316", order: 1 },
      { label: "Inciting Incident", description: "The event that sets everything in motion", color: "#eab308", order: 2 },
      { label: "Rising Action", description: "Escalating tension and complications", color: "#eab308", order: 3 },
      { label: "Midpoint", description: "A twist or revelation that changes the trajectory", color: "#ef4444", order: 4 },
      { label: "Crisis", description: "The darkest moment — all seems lost", color: "#ef4444", order: 5 },
      { label: "Climax", description: "The decisive confrontation or turning point", color: "#8b5cf6", order: 6 },
      { label: "Resolution", description: "The new normal after the climax", color: "#22c55e", order: 7 },
    ],
  },
  {
    id: "hero-journey",
    name: "Hero's Journey",
    description: "Campbell's monomyth adapted for short-form video.",
    beats: [
      { label: "Ordinary World", description: "Show the hero in their everyday life", color: "#64748b", order: 0 },
      { label: "Call to Adventure", description: "Something disrupts the status quo", color: "#f97316", order: 1 },
      { label: "Refusal / Doubt", description: "Hesitation before committing", color: "#eab308", order: 2 },
      { label: "Crossing the Threshold", description: "The hero enters the new world", color: "#3b82f6", order: 3 },
      { label: "Trials & Allies", description: "Challenges faced and allies met", color: "#8b5cf6", order: 4 },
      { label: "Ordeal", description: "The ultimate test", color: "#ef4444", order: 5 },
      { label: "Reward", description: "The hero gains what they sought", color: "#22c55e", order: 6 },
      { label: "Return", description: "The hero returns transformed", color: "#06b6d4", order: 7 },
    ],
  },
  {
    id: "before-after",
    name: "Before / After",
    description: "Transformation arc — show the contrast between then and now.",
    beats: [
      { label: "The Problem", description: "Show the pain point or starting state", color: "#ef4444", order: 0 },
      { label: "The Turning Point", description: "What changed or what was discovered", color: "#eab308", order: 1 },
      { label: "The Process", description: "Show the journey or method", color: "#3b82f6", order: 2 },
      { label: "The Result", description: "Reveal the transformation", color: "#22c55e", order: 3 },
      { label: "CTA", description: "Call to action — what should the viewer do next?", color: "#8b5cf6", order: 4 },
    ],
  },
  {
    id: "tension-release",
    name: "Tension & Release",
    description: "Build suspense, then deliver the payoff. Great for reveals.",
    beats: [
      { label: "Tease", description: "Hint at what's coming without revealing it", color: "#f97316", order: 0 },
      { label: "Build", description: "Layer tension through pacing, music, visuals", color: "#eab308", order: 1 },
      { label: "Peak Tension", description: "Maximum suspense — the audience is on the edge", color: "#ef4444", order: 2 },
      { label: "The Reveal", description: "Deliver the payoff or surprise", color: "#8b5cf6", order: 3 },
      { label: "Reaction", description: "Let the audience absorb the impact", color: "#22c55e", order: 4 },
    ],
  },
  {
    id: "day-in-life",
    name: "Day in the Life",
    description: "Chronological slice-of-life format — morning to night.",
    beats: [
      { label: "Wake Up", description: "Morning routine, setting the tone", color: "#f97316", order: 0 },
      { label: "Morning", description: "First activities, heading out", color: "#eab308", order: 1 },
      { label: "Midday", description: "Core activity or work", color: "#3b82f6", order: 2 },
      { label: "Afternoon", description: "Continuation, a shift or event", color: "#8b5cf6", order: 3 },
      { label: "Evening", description: "Wind down, reflection", color: "#06b6d4", order: 4 },
      { label: "Night", description: "Closing moment, ending shot", color: "#64748b", order: 5 },
    ],
  },
  {
    id: "listicle",
    name: "Listicle / Top N",
    description: "Countdown or list format — each item is a beat.",
    beats: [
      { label: "Intro / Hook", description: "Set up the list topic and hook viewers", color: "#f97316", order: 0 },
      { label: "Item 1", description: "First list item", color: "#3b82f6", order: 1 },
      { label: "Item 2", description: "Second list item", color: "#8b5cf6", order: 2 },
      { label: "Item 3", description: "Third list item", color: "#22c55e", order: 3 },
      { label: "Item 4", description: "Fourth list item", color: "#eab308", order: 4 },
      { label: "Item 5", description: "Fifth list item (the best one)", color: "#ef4444", order: 5 },
      { label: "Outro / CTA", description: "Wrap up and call to action", color: "#06b6d4", order: 6 },
    ],
  },
  {
    id: "tutorial",
    name: "Tutorial / How-To",
    description: "Step-by-step instructional format.",
    beats: [
      { label: "Hook / Problem", description: "Show what the viewer will learn or achieve", color: "#f97316", order: 0 },
      { label: "What You Need", description: "Materials, tools, or prerequisites", color: "#64748b", order: 1 },
      { label: "Step 1", description: "First step with clear visuals", color: "#3b82f6", order: 2 },
      { label: "Step 2", description: "Second step", color: "#8b5cf6", order: 3 },
      { label: "Step 3", description: "Third step", color: "#22c55e", order: 4 },
      { label: "Final Result", description: "Show the completed result", color: "#eab308", order: 5 },
      { label: "Tips & CTA", description: "Pro tips and call to action", color: "#06b6d4", order: 6 },
    ],
  },
  {
    id: "blank",
    name: "Blank Canvas",
    description: "Start from scratch with no predefined beats.",
    beats: [],
  },
];
